version: 0.1
environment_variables:
 plaintext:
  JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
phases:
 install:
  commands:
   - echo Not installing anything this time
 pre_build:
  commands:
   - echo Nothing to do
   - echo `$MAVEN_HOME`
   - mvn -version
 build:
  commands:
   - echo Build started on `date`
   - mvn install
 post_build:
  commands:
   - echo Build completed on `date`
artifacts:
 files:
  - "**/*"
 discard_paths: no